AWSTemplateFormatVersion: '2010-09-09'
Description: 'ddr'

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-c7f118bf
      InstanceType: p2.xlarge
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SecGroup
      Tags:
      - Key: "Name"
        Value: "ddr"

  SecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ddr-secgroup
      GroupDescription: ddr-secgroup
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      #SecurityGroupEgress:
      #- IpProtocol: tcp
      #  FromPort: '80'
      #  ToPort: '80'
      #  CidrIp: 0.0.0.0/0
      #Tags:
      #- Resource Tag
      #VpcId: vpc-5ea44d39
      Tags:
      - Key: "Name"
        Value: "ddr-secgroup"

Parameters:
  KeyName:
    Default: sshvans
    Description: EC2 key name
    Type: String

Outputs:
  InstanceId:
    Value: !Ref Instance
