AWSTemplateFormatVersion: '2010-09-09'
Description: ddr-raspi

Resources:
  Bucket:
    Type: "AWS::S3::Bucket"

  User:
    Type: "AWS::IAM::User"
    Properties: 
      UserName: DdrRaspi
      Policies:
      - PolicyName: DdrRaspiPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: S3Access
            Effect: Allow
            Action:
            - s3:PutObject*
            Resource:
            - !Sub "arn:aws:s3:::${Bucket}/*"

Outputs:
  User:
    Value: !Ref User
  Bucket:
    Value: !Ref Bucket
